### ISSUE TITLE
検索機能

### ISSUE THREAD

**Issue by kenta-wakasa** [flutteruniv/bax#12]

**Comment by kuwabara-hirokazu** [comment]
* 検索したワードに対してFirestoreからマッチする施設を返す
* 検索窓の下に結果を表示する or 該当施設一覧結果画面に遷移させる
* 検索結果には最低限 施設名 + Wifi速度を表示させる
* タップしたら施設詳細画面にとぶ想定

**Comment by kenta-wakasa** [comment]
部分一致、有料でもいいので、ちゃんと作ってもいいと思います。
なにかよさそうなものがあれば、提案してください。

今回は施設名のみでいったん検索をかけれればいいので、こんな手法もあります。
こいつはこいつで優れてると思っています。

https://qiita.com/oukayuka/items/d3cee72501a55e8be44a

**Comment by kenta-wakasa** [comment]
こう言った方法もあるようです。

https://stackoverflow.com/questions/46568142/google-firestore-query-on-substring-of-a-property-value-text-search

**Comment by kuwabara-hirokazu** [comment]
MeilisearchというAlgoliaよりも低価格でFirestoreの全文検索を実現するExtensionもあるらしいです。
ただ、この人の記事によると検索性能はまだ不安定かも。
もうちょい調査が必要。

https://zenn.dev/tsuruo/articles/939f9af76f83be#%E6%A4%9C%E7%B4%A2%E6%80%A7%E8%83%BD%E3%81%8C%E5%B0%91%E3%81%97%E5%BE%AE%E5%A6%99%E3%81%8B%E3%82%82

**Comment by kenta-wakasa** [comment]
GoogleMapAPIを使うという方法もあるみたい。
それっぽい名前の施設をサジェストしてくれる。

https://qiita.com/ninoko1995/items/55aa7bcea10f13940cfc

**Comment by kuwabara-hirokazu** [comment]
>GoogleMapAPIを使うという方法もあるみたい。
それっぽい名前の施設をサジェストしてくれる。

そもそも、GoogleMapApiから取得した施設名でFirestoreに保存しているはずだから、
ユーザの入力した文字列からGoogleMapAPi検索でヒットした施設を取得してきて、それに対して
`.where('name', arrayContains: 'マッチした施設名一覧')`すれば要件満たせるかも？
部分一致機能つくらなくても完全一致で検索できる説。

**Comment by kuwabara-hirokazu** [comment]
N-gram 検索の致命的なデメリットが見つかったので追記

・多言語での検索に対応できない
例えば「東京プリンスホテル」でFirestoreに保存しているときは「Tokyo Prince Hotel」「东京王子大饭店」では検索ヒットしない

baxはグローバルで利用されることを想定しているので、日本のホテルは日本語でしか検索できないというのは微妙。
少なくとも英語での検索はできるようにしたい。

**Comment by kuwabara-hirokazu** [comment]
GoogleMapのPlace APiをPostamanでいくつか試してみたところ、Place AutocompleteというAPIが良さげだった！
* 部分一致検索ができ、予測結果を返してくれる
* typesでlodging(宿泊)を指定することで無駄な施設を省くことができる
* 多言語対応。「東京プリンスホテル」「Tokyo Prince Hotel」「东京王子大饭店」(簡体中文)でも同じ施設情報が返ってくる

https://developers.google.com/maps/documentation/places/web-service/autocomplete

**Comment by kenta-wakasa** [comment]
Place Autocomplete よさそうですよね！
でてきた PlaceId と Firestore のデータは紐づけできるわけで、そこからWiFiの計測結果があるのかないのかも出せそう。

**Comment by kuwabara-hirokazu** [comment]
☝️を踏まえて下記の検索仕様はどうでしょうか？

## 検索仕様案
* インクリメンタルサーチでユーザーが文字を入力するたびに Place Autocomplete APIを叩いて、入力フォームの下に施設名候補を表示する（GoogleMapアプリの検索をイメージ）
* ユーザーが候補をタップする（候補が何も表示されなかった場合はタップするものがないのでFirestoreに検索をかけない）
* 結果画面に遷移する
* Firestoreから選択された候補の施設IDとマッチする施設があれば表示する（施設IDを検索キーにすることで完全一致で検索できる）

**Comment by kenta-wakasa** [comment]
インクリメンタルサーチしたい。ただ料金も知っておきたい。
Place Autocomplete APIはどれくらいの価格でしょう？


dartだとgoogle_maps_webserviceというパッケージからお気軽に呼び出せます。
もちろん生でhttp通信しても良さそう。

**Comment by kuwabara-hirokazu** [comment]
>インクリメンタルサーチしたい。ただ料金も知っておきたい。
Place Autocomplete APIはどれくらいの価格でしょう？

ですよね。調べますのでお待ちを。

>dartだとgoogle_maps_webserviceというパッケージからお気軽に呼び出せます。

google_maps_webserviceなんですけど2年前で更新止まってるので、生でやったほうがよさそうかなって思ってます

**Comment by kenta-wakasa** [comment]
生で自分たちが使いやすいような設計にしましょう！

**Comment by kuwabara-hirokazu** [comment]
めっちゃ雑ですが仮に毎日100人が10文字の施設を１回検索した場合、10リクエスト * 100人 * 30日 = 30,000リクエストで
84.9$ （10,857.44 円）になりました。
これは費用がはね上がる予感。。。

![スクリーン ショット 2023-01-14 に 21 07 28 午後](https://user-images.githubusercontent.com/62511320/212470942-a2fe9673-d233-4187-9b8d-63a10906fbe4.png)


https://mapsplatform.google.com/pricing/?_gl=1%2Amdc2dc%2A_ga%2AMTkyMDIxOTkzNC4xNjM2OTM4ODAz%2A_ga_NRWSTWS78N%2AMTY3MzY5NzUxMS42LjEuMTY3MzY5NzU4MC4wLjAuMA..#pricing-grid

**Comment by kuwabara-hirokazu** [comment]
first開発では普通の検索機能で検索リクエスト数だけ計測できるようにしておいて、
利用実態に応じてインクリメンタルサーチを検討するでもいいかもですね。

**Comment by kenta-wakasa** [comment]
たけーけど、インクリメントサーチやっちゃいましょう。
赤にならない設計だったらなんとかなるはず。

**Comment by kuwabara-hirokazu** [comment]
Wow！
了解です！そしたら実装フェーズに入りますね

**Comment by kuwabara-hirokazu** [comment]
[メモ]
パラメータにlocation (緯度経度)と radius(距離)をつけることで該当範囲の施設が優先的に返ってくるらしい。
現在地から○kmとかで設定してもいいかも。

https://developers.google.com/maps/documentation/places/web-service/autocomplete#location_biasing

**Comment by kuwabara-hirokazu** [comment]
予測結果が返ってきてからの次のアクションを再考してみました。
下記の仕様どうでしょうか？ 

```
・ GoogleMapの予測結果をタップする
・ タップした施設の緯度経度を取得してMap移動
・ Markerがあれば吹き出しが表示されてダウンロード速度を確認できる
   (吹き出しをタップすると施設詳細画面に遷移して更に詳細情報が見れる)
・ Markerなければ「計測結果なしMarker」を一時的に作って表示する
```

リリース当初は検索したところでデータがたまってないのでほとんど計測結果なしになると思います。
でも、目当ての施設の計測結果がなくても、その付近にMarkerが立ってるホテルがあれば そこに泊まろうかなってなるかもしれません。
「検索意味ねぇじゃん」っていうマイナスイメージを少しは緩和できるのかなと思ってます。


下記は結果ありなしパターンそれぞれのイメージです。

https://user-images.githubusercontent.com/62511320/212922035-303da6e8-7b7c-4f4f-a6e1-a62d8bd5bacb.mp4

https://user-images.githubusercontent.com/62511320/212922089-75f92efc-5c26-4e74-8291-d016d6eb75fd.mp4

**Comment by kenta-wakasa** [comment]
めちゃいいじゃん！

**Comment by kenta-wakasa** [comment]
Wi-Fi測定結果なしのところにはBAXボーナスを付与する予定なので、ボーナス目当ての人も検索を使うかも。
無課金の人は使えない予定だけども。

**Comment by kuwabara-hirokazu** [comment]
たしかに最初はそっちの使い方のほうが多いかもですね！

**Comment by kuwabara-hirokazu** [comment]
@kenta-wakasa 
ただ、上の仕様を実現する上でネックなのが 予測結果(Place Autocomplete API)に緯度経度が含まれていないことです😂
ので、選択した施設の緯度経度を求める処理が必要になってくるのですが、[Geocoding API](https://developers.google.com/maps/documentation/javascript/geocoding?hl=ja#GeocodingRequests)を使ってもいいでしょうか？

一応無料で緯度経度検索ができるAPIもいくつかあったけど、個人が開発したものだったり実験的と名付けられていたりであまり信用できなさそう。

![image](https://user-images.githubusercontent.com/62511320/213045697-b1e4913b-581c-4881-9c6a-e2ff8b1d86ac.png)

**Comment by kenta-wakasa** [comment]
確か、プレイスIDで詳細を検索ってのがあった気がする！
そこに緯度経度もある。

**Comment by kenta-wakasa** [comment]
あ、でもこのAPIがそれなのか。

**Comment by kenta-wakasa** [comment]
僕がいってたのはこれだったわ。
https://developers.google.com/maps/documentation/places/web-service/details#PlaceDetailsRequests

**Comment by kuwabara-hirokazu** [comment]
Place Detailのほうが高ぇのでやめたほうがいいです

<img width="815" alt="image" src="https://user-images.githubusercontent.com/62511320/213054636-6915f115-ec79-4cc8-acab-6cfd3f03959c.png">

**Comment by kenta-wakasa** [comment]
高いんかい！
3倍以上じゃん。

Geocoding使いましょう。
すでに施設登録済みのやつは、そっから引っ張ってくる仕組みもつくれれば安くすみそう。

**Comment by kuwabara-hirokazu** [comment]
OKです

>すでに施設登録済みのやつは、そっから引っ張ってくる仕組みもつくれれば安くすみそう。

ですね🙆 その方針で進めます
