### ISSUE TITLE
SNSシェア機能

### ISSUE THREAD

**Issue by kenta-wakasa** [flutteruniv/bax#15]

**Comment by kenta-wakasa** [comment]
作っていただいたダイアログを画像化してSNSで投稿する機能をつけましょう！

**Comment by kenta-wakasa** [comment]
@tora666 
ちょうど自分が前に書いていた記事が！
https://zenn.dev/pressedkonbu/books/flutter-reverse-lookup-dictionary/viewer/011-widget-to-image

**Comment by tora666** [comment]
- 頂いたURLを元に画像化に成功（多分）
- シェア機能には一番popularityが高いshare_plusを使いたい...
[share\_plus \| Flutter Package](https://pub.dev/packages/share_plus) 
- このパッケージだとWebとも互換性の強いXFileを引数として渡すらしい
- イメージ化したものをXFileにするには...? ⇦ 今ここ

なかなか進まず申し訳ないです...！
一応進捗をあげておきます🙇‍♀️

**Comment by tora666** [comment]
- Uint8Listに変換 → XFile.fromData(Uint8List型のデータ)で変換できたっぽい
- Androidで検証↓ ドライブに保存できた
<img width="244" alt="スクリーンショット 2023-01-25 0 49 51" src="https://user-images.githubusercontent.com/45866095/214341138-c98572e4-ee9f-4217-9130-e307430a5d60.png">

- 枠がないとちょっと変かも...
- ダイアログだけじゃなくてページ全体をスクショする...？

**Comment by tora666** [comment]
- リップルエフェクトを消す
  - `Colors.transparent`じゃ消えなかった...
  - 背景色と同じ色を設定したら消えたのでとりあえずそれで...
-  XFile.fromData、他にも引数指定する？
   - https://pub.dev/documentation/cross_file/latest/cross_file/XFile-class.html
   - ファイル名が...
      <img width="462" alt="スクリーンショット 2023-01-25 17 38 23" src="https://user-images.githubusercontent.com/45866095/214516755-8421dec2-7423-42cb-acf4-6062035cf5ac.png">
- 背景色を付けようか、ボーダーを付けようか、ページ全体をスクショしようか悩ましいところですが、その辺りはデザインが決まってからで良いですかね？ @kenta-wakasa

**Comment by tora666** [comment]
<img width="445" alt="スクリーンショット 2023-01-26 22 27 20" src="https://user-images.githubusercontent.com/45866095/214860351-d5a85197-1143-49bc-913b-600f66579059.png">

`mimeType`を指定したらシェア先を指定する画面はいい感じに...!
(指定する前はここにファイル名がでてました)
ただ、ドライブに保存した時のファイル名は前回と変わらずのIDみたいな文字列 + `.png`で`5234ac9e-3a07-442f-9c30-fde94b1f2a37.png` になりました。
`name`も指定しているのになぜでしょう...
もう少し調査してみます！

**Comment by tora666** [comment]
- [renameSync メソッド \- File クラス \- dart:io ライブラリ \- Dart API](https://api.flutter.dev/flutter/dart-io/File/renameSync.html)
- [renameSyncについての参考サイト](https://teratail.com/questions/362137?sort=2)

ファイル名、解決できず...
`renameSync`に渡すパスがうまく設定できていない様子？
とりあえずissue残して先に進もうと思います🙇‍♀️
