### ISSUE TITLE
メールアドレス認証機能

### ISSUE THREAD

**Issue by kenta-wakasa** [flutteruniv/bax#20]
これが参考になりそう！

https://firebase.google.com/docs/auth/flutter/email-link-auth?hl=ja&authuser=3

**Comment by kenta-wakasa** [comment]
どこかに仮の設定画面を用いて、メールアドレス認証ができるかのテストをする。
単純な新規アカウント作成処理ではなく、アノニマスでログインしている現在のアカウントと、そのメールアドレスをリンクさせる処理。

**Comment by kuwabara-hirokazu** [comment]
https://flutteruniv.slack.com/archives/C04HS5RTYM7/p1675173205165709?thread_ts=1675172191.453509&cid=C04HS5RTYM7
