### ISSUE TITLE
アカウントの削除機能の追加

### ISSUE THREAD

**Issue by Umigishi-Aoi** [flutteruniv/bax#37]
> 2022年6月30日以降、アカウントの作成に対応したAppをApp Storeに提出する場合は、ユーザー自身がそのApp内でアカウントを削除できるようにする必要があります。

ということでアカウントの削除機能の実装がiOSでリリースするためには必須となります。

参考：
https://developer.apple.com/jp/support/offering-account-deletion-in-your-app/

**Comment by kenta-wakasa** [comment]
これはやんないとダメですね。
匿名認証でやろうと思ってるので、そこまで大変じゃない？

**Comment by kenta-wakasa** [comment]
なくても怒られなかったので、なしでいっか。
