### ISSUE TITLE
fvm の導入

### ISSUE THREAD

**Issue by Umigishi-Aoi** [flutteruniv/bax#38]
Flutterのバージョンマネジメントツール、FVMの導入を検討いただきたいです。

少々複雑になるので要相談ではあるのですが、
自分はFlutterのバージョンをガンガン最新に上げていくので、
メンバーと足並み揃えるためには必要かな、と思っています。

(全員で最新バージョンにする、とルール付けられたら導入しなくて良いかと思います)

**Comment by kenta-wakasa** [comment]
stableの最新版を常に使う、という取り決めにしたいと思います！
リリースされて安定運用しなければいけないってなったら、fvmの導入考えたいですね。
