### ISSUE TITLE
静的解析の強化 (pedantic_monoの導入)

### ISSUE THREAD

**Issue by Umigishi-Aoi** [flutteruniv/bax#39]
要相談ではありますが、
静的解析の強化([pedantic_mono](https://pub.dev/packages/pedantic_mono)の導入)をしたいです。

pedantic_monoの導入メリットとしては、
静的解析に従うことで、メンバー間の書き方の違いがある程度矯正され、統一的な書き方ができることです。

- コンストラクタの書き順

- 『' '』か『" "』か 

特にpedantic_monoはデフォルトのflutter_lintより厳しく設定されているため、
よりコードの矯正が行われ、統一的な書き方(設定したlintルールに従った書き方)ができるようになります。

デメリットとしては、
静的解析に従うことに伴うコード修正による、作業時間の増加でしょうか。
コードレビューでの手戻りが減るので、一長一短かなとも思います。

以上、検討をよろしくお願い致します。

**Comment by kenta-wakasa** [comment]
導入しました！
ルールの追加、削除については気軽に意見を言い合いましょう！
