### ISSUE TITLE
課金機能の調査

### ISSUE THREAD

**Issue by Umigishi-Aoi** [flutteruniv/bax#40]
bax で導入する課金機能の構築を検討する。

- 課金機能でやりたいことの整理
- 自前実装とrevenue catの比較

検討内容をコメントに記載していきます。

**Comment by Umigishi-Aoi** [comment]
課金機能でやりたいこと(実装を検討しなきゃいけないこと)
- サブスクリプションでのBAX(ポイント)の付与
- BAXの単発購入機能

revenue cat
https://www.revenuecat.com/

自前実装
https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases#0

revenue cat は月$10,000 までは無料プランで可、
超えるようなら$1,000 ごとに $8のお金がかかる
バックエンドを任せられるので、安心感はあるが、自由度はない(どのユーザーがどのプランか判断しづらい)

自前実装のバックエンドはFirebase(Firestore&cloud Firestore)
書き込みコスト＆定期実行のコストで済むので、コストは抑えられるはず。
バックエンド自前実装の場合、自由度はある。
ただ、実装速度は落ち、revenue catほどの安心感(外部クラックに対する対策など)は十分でないかもしれない

**Comment by kenta-wakasa** [comment]
RevenueCatsで実装してもうた
