### ISSUE TITLE
Wi-Fiの測定UX調査

### ISSUE THREAD

**Issue by kenta-wakasa** [flutteruniv/bax#41]
他のWi-Fi測定アプリがどんな情報をどういうUIで示しているんだろうというインプット

ここにコメントで事例出していければと思います！

**Comment by kenta-wakasa** [comment]
https://fast.com/ja/#

https://user-images.githubusercontent.com/66857966/211335435-8736c137-e8e6-40d7-b89d-bb1831db41d1.mp4

![CleanShot 0005-01-09 at 23 46 16](https://user-images.githubusercontent.com/66857966/211335500-b37c03ce-20ef-45ae-86ac-74b2b206027f.png)

**Comment by kenta-wakasa** [comment]
https://www.speedtest.net のアプリ版

https://user-images.githubusercontent.com/66857966/211336494-1606f07a-444f-41ce-916f-880e16401dea.mov

**Comment by tora666** [comment]
![IMG_9463](https://user-images.githubusercontent.com/45866095/212253071-70285012-6c02-4f8c-ad19-ed4e3dfabf19.PNG)

> 4Kで映画を鑑賞することもできます！

↑こういうの嬉しい。
慣れてくれば数値で判断できるけど、大抵は（私も含め）数値だけだと速いか遅いかわからない...

**Comment by kenta-wakasa** [comment]
たしかに！
これ大事

**Comment by tora666** [comment]
- 吹き出しを探したのですが、なかなかいい形に出会えず、自作しました。
- ピンはまだ探し中です！
- 速度の評価を言語化するのではなく、星とかLvとかで表すのも分かりやすいかなと思い、とりあえず星を置いてみました。
- 速度表示ですが、ダウンロードとアップロードの2つの値を置くより、ひとつの方が情報が入ってきやすいのかなと思ったり...、詳細情報として小さめに表示してみるのが良いかもと思ったり...、ご意見をいただければ...
  - 他のアプリも調査しましたが、値が一つのところ、二つのところ、三つのところなど様々でした！ 
- シェアボタン、アイコンがいいかアイコン＋テキストか悩むところ...
  - `Stack`で作ったので配置が少し難しい... 

<img width="522" alt="スクリーンショット 2023-01-14 3 19 01" src="https://user-images.githubusercontent.com/45866095/212391550-b8926a30-4c49-4a11-8e74-e6be3a9ed78d.png">

**Comment by kenta-wakasa** [comment]
お！
楽しい感じになってて素敵です！

ダウンロード速度だけの表示でいいと思います！多くの人はそっちを見るので。

マップ上では今、3段階くらいを考えていますが、星などで良さをビジュアライズしていく方向性はめちゃよきです。

シェアボタン、シェアして欲しすぎるので、文字入りのボタンがいいかなーと思ってます。よくあるシェアマークさりげなさすぎて気づかないので。

**Comment by tora666** [comment]
> シェアボタン、シェアして欲しすぎるので、文字入りのボタンがいいかなーと思ってます。よくあるシェアマークさりげなさすぎて気づかないので。

分かります！なかなか伝わらないアイコンですよね...
テキスト + アイコンで作ってみます💪

> ダウンロード速度だけの表示でいいと思います！多くの人はそっちを見るので。

こちらも承知しました！

> マップ上では今、3段階くらいを考えていますが、星などで良さをビジュアライズしていく方向性はめちゃよきです。

三段階！なるほどです。どんなモチーフになるにせよ、3つ並べておきますね！

**Comment by tora666** [comment]
#### ピン

↓ シンプルにまち針みたいなのかわいい...
  <img width="384" alt="スクリーンショット 2023-01-18 17 28 14" src="https://user-images.githubusercontent.com/45866095/213121211-37a20a55-251f-404a-9c37-7930dc7aba23.png">

↓ こういうのでwi-fiマーク入ってるといいかも
  <img width="416" alt="スクリーンショット 2023-01-18 17 29 02" src="https://user-images.githubusercontent.com/45866095/213121393-2fe92978-92c3-47db-820f-d26f7988d6f5.png">

**Comment by tora666** [comment]
- wifi + pin 
  吹き出しと形がかぶってる...
  wifi部分の背景色は透明より白のが良さそう？
<img width="333" alt="スクリーンショット 2023-01-18 18 00 42" src="https://user-images.githubusercontent.com/45866095/213128079-0e578049-274c-474e-a786-2f26427f9f18.png">

- 📌
  これも目立たず...
  真ん中抜かずに色入れたら目立つかもしれない
<img width="333" alt="スクリーンショット 2023-01-18 18 11 57" src="https://user-images.githubusercontent.com/45866095/213130675-6ff34c3e-43f1-4c6c-b53d-32bd5b68e82d.png">

- まち針
<img width="311" alt="スクリーンショット 2023-01-18 18 19 01" src="https://user-images.githubusercontent.com/45866095/213132126-6f1eb1d1-9599-4aa9-ad31-8c08feaae14e.png">

pinの形は相談するとして、必要な要素は揃ったのでpushします！
