### ISSUE TITLE
Firebase の再設定の推奨

### ISSUE THREAD

**Issue by Ryotaewamoto** [flutteruniv/bax#44]
## やること
- 開発環境、本番環境の Firebase のプロジェクトを再度作成する。その上で google-services.json 等のファイルを gitignore する。

## 理由
このリポジトリはパブリックなリポジトリであり、誰でも ``git clone`` が可能です。そのため ``git clone`` を行なったユーザはローカルの環境でデバッグビルド可能になります。ここでマップのAPIキーは git で追跡されていませんが、Firebase の google-services.json 等は追跡されており、マップ関連のコードを削除してデバッグビルドした場合を考えます。この場合、そのユーザは Firestore 等にデータを追加したり、データを更新、削除したりすることが可能になると予想されます。このような不特定多数の人が Firestore のデータを（コンソールは見れないとはいえ）操作できるのは危ないと思いました。

**Comment by kenta-wakasa** [comment]
ありがとう！
これはセキュリティルールをがちがちに書くという自戒のために公開しています。

だけど、Wi-Fi測定してBAXを付与の特性上、セキュリティルールを書いても不正な投稿は防げないんじゃないかと思ってきました。
これは僕の脳みそが足りないだけな可能性もあるので、なにか策を今考えています。
策がなかったら少なくとも本番用は作り直します。

**Comment by kenta-wakasa** [comment]
auth情報に端末の位置情報とか込められたら勝てそうだけどもねえ。
そんなの無理だよねえ。
特殊な秘密鍵みたいなものを独自で発行して、それをリクエストに込めるとか？
そしたらその秘密鍵書かれているdartファイルだけignoreしたら、解決しそう。

**Comment by kenta-wakasa** [comment]
BAX付与は、cloud_functions 経由でやらないと、ユーザーが書き込み放題になってしまうので、よくない。
かと言ってコードが全部公開されているので、BAX付与のためのトリガーがばれたら、不正できてしまうという。。。

**Comment by KosukeSaigusa** [comment]
文脈理解していないので的外れかもしれませんが...

- Firebase の設定ファイルを GitHub で公開していようがいまいが、API キーは知ろうと思えば（詳しい人がやればかんたんに）知れるので、根本的には意味がない（まあ公開してなくていいファイルはしなくていいとは思う）。Git の追跡対象外だから大丈夫だろうと誤解してはいけない
- 今回のニーズに完璧に沿うかはわかりませんが、信頼できるクライアントのみ Firestore への読み書きや、Cloud Functions の実行を許すには、Firebase App Check を使うと良いかも

**Comment by kenta-wakasa** [comment]
Firebase App Check みてみよう

**Comment by kenta-wakasa** [comment]
たぶん、Firebase App Check で Storeからダウンロードされた署名付きのアプリかどうかみたいな判定ができれば、この問題は解決する。

**Comment by Ryotaewamoto** [comment]
自分は、デバッグ環境なら Firestore のデータを（セキュリティルール上の問題がなければ）操作し放題ではないか、と考えていました。

> 今回のニーズに完璧に沿うか調査が必要だが、信頼できるクライアントのみ Firestore への読み書きや、Cloud Functions の実行を許すには、Firebase App Check の使用を検討すると良さそう

この問題は Firebase App Check のデバイストークンの設定で解決できそうです！

@KosukeSaigusa 
ありがとうございます！

参考：
[Firebase ドキュメント（Flutterを使用してデバッグプロバイダーでAppCheckを使用する）](https://firebase.google.com/docs/app-check/flutter/debug-provider)

**Comment by kenta-wakasa** [comment]
App Checkやらないと！
