### ISSUE TITLE
ロガーパッケージの導入

### ISSUE THREAD

**Issue by kuwabara-hirokazu** [flutteruniv/bax#53]
* すささんのやつを入れる
  * https://zenn.dev/susatthi/articles/20220506-144617-flutter-roggle

* printでログ出してる箇所を置き換える

**Comment by kenta-wakasa** [comment]
これ、ひとまず手をつけてもらいましょうか。
課金機能、設定とかやっぱりアドミンの人しかやりづらいと思うので。
