### ISSUE TITLE
WiFi測定結果の投稿機能

### ISSUE THREAD

**Issue by kenta-wakasa** [flutteruniv/bax#54]
WiFiの測定結果を投稿する機能を作成する。

WiFIの測定結果は Facility に組み込まれるが、測定結果単体でもどこかにコレクションを持っておいた方が良さそうな気がする。

実際の測定結果は直近3つの平均値をとるなりで、新しいのから順に重みづけする必要がありそう。

これらの処理をクライアント側でやるよりもfunctionsを使ってやるべきではないかと思っている。

既存のデータを取得してきて、それらの平均をとって更新みたいな処理は長すぎるので、サーバー側で勝手にやっていて欲しい。

また、ユーザーは同じ施設に対して、一日に一度の投稿しかできないように制限をかけるべきだと思う。
何度も更新する意味はないし、何度も投稿できるとBAX付与時に不具合が生じる。

**Comment by kenta-wakasa** [comment]
メモ
2023-01-26-uid-placeId

**Comment by kenta-wakasa** [comment]
サーバータイムスタンプの値を事前にとってこれるのか。

**Comment by kuwabara-hirokazu** [comment]
@kenta-wakasa 

>サーバータイムスタンプの値を事前にとってこれるのか。

これキツそう。方法が見つけられなかったです。

厳密にやるならfunctionsで更新したほうがいいかも 。
クライアントでは端末の時刻でチェックしておいて、functionsで更新する前にservertimeでもチェックするという二段構えにするとか。

**Comment by kenta-wakasa** [comment]
セキュリティルールで、ほんとに今日なのかどうかチェックできたら良さそう。

**Comment by kuwabara-hirokazu** [comment]
お〜たしかに。それならfunctionsなしでいけますね。
request.timeでservertimeとれるっぽいのでチェックできそう

**Comment by kenta-wakasa** [comment]
それだ！
